import { Movie } from "./constants";

export const movies: Movie[] = [
  {
    genre_id: 1,
    title: "Underdog",
    year: "2007",
    rated: "PG",
    released: "03 Aug 2007",
    runtime: "84 min",
    genre: "Action, Adventure, Comedy, Family, Fantasy, Sci-Fi",
    director: "Frederik Du Chau",
    writer:
      "Adam Rifkin (screenplay), Joe Piscatella (screenplay), Craig A. Williams (screenplay), Joe Piscatella (story), Craig A. Williams (story), Adam Rifkin (story), W. Watts Biggers (television series)",
    actors: "Jason Lee, Peter Dinklage, Jim Belushi, Patrick Warburton",
    plot: "A Beagle must use his newly-bestowed superpowers to defend Capitol City from mad scientist Simon Barsinister.",
    language: "English",
    country: "USA",
    awards: "3 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTk5NjkyNzEwOV5BMl5BanBnXkFtZTcwODc5NDI1MQ@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "10/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "16%",
      },
      {
        source: "Metacritic",
        value: "37/100",
      },
    ],
    metascore: "37",
    imdbRating: "4.7",
    imdbVotes: "19,729",
    imdbID: "tt0467110",
    type: "movie",
    DVD: "08 Jul 2016",
    boxOffice: "$43,760,605",
    production: "Spyglass Entertainment",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 1,
    title: "Honest Thief",
    year: "2020",
    rated: "PG-13",
    released: "16 Oct 2020",
    runtime: "99 min",
    genre: "Action, Crime, Drama, Thriller",
    director: "Mark Williams",
    writer:
      "Steve Allrich, Mark Williams, Steve Allrich (story by), Mark Williams (story by)",
    actors: "Liam Neeson, Kate Walsh, Jai Courtney, Jeffrey Donovan",
    plot: "Wanting to lead an honest life, a notorious bank robber turns himself in, only to be double-crossed by two ruthless FBI agents.",
    language: "German, English, Spanish",
    country: "USA",
    awards: "1 nomination.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjEwNjYyMTMtODc5Yi00NTg5LTkwMzAtZTkyOTcyNTFkMGIyXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "6.0/10",
      },
      {
        source: "Metacritic",
        value: "46/100",
      },
    ],
    metascore: "46",
    imdbRating: "6.0",
    imdbVotes: "23,614",
    imdbID: "tt1838556",
    type: "movie",
    DVD: "N/A",
    boxOffice: "$14,163,574",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 1,
    title: "Star Wars: Episode III - Revenge of the Sith",
    year: "2005",
    rated: "PG-13",
    released: "19 May 2005",
    runtime: "140 min",
    genre: "Action, Adventure, Fantasy, Sci-Fi",
    director: "George Lucas",
    writer: "George Lucas",
    actors: "Ewan McGregor, Natalie Portman, Hayden Christensen, Ian McDiarmid",
    plot: "Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-Wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.",
    language: "English",
    country: "USA",
    awards: "Nominated for 1 Oscar. Another 26 wins & 62 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "7.5/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "80%",
      },
      {
        source: "Metacritic",
        value: "68/100",
      },
    ],
    metascore: "68",
    imdbRating: "7.5",
    imdbVotes: "714,007",
    imdbID: "tt0121766",
    type: "movie",
    DVD: "10 Apr 2015",
    boxOffice: "$380,270,577",
    production: "Lucasfilm Ltd.",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 1,
    title: "Deadpool",
    year: "2016",
    rated: "R",
    released: "12 Feb 2016",
    runtime: "108 min",
    genre: "Action, Adventure, Comedy, Sci-Fi",
    director: "Tim Miller",
    writer: "Rhett Reese, Paul Wernick",
    actors: "Ryan Reynolds, Karan Soni, Ed Skrein, Michael Benyaer",
    plot: "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.",
    language: "English",
    country: "USA",
    awards: "Nominated for 2 Golden Globes. Another 28 wins & 76 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "8.0/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "85%",
      },
      {
        source: "Metacritic",
        value: "65/100",
      },
    ],
    metascore: "65",
    imdbRating: "8.0",
    imdbVotes: "904,840",
    imdbID: "tt1431045",
    type: "movie",
    DVD: "21 Apr 2016",
    boxOffice: "$363,070,709",
    production: "Kinberg genre, Donners&#39; Company",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 2,
    title: "Bruce Almighty",
    year: "2003",
    rated: "PG-13",
    released: "23 May 2003",
    runtime: "101 min",
    genre: "Comedy, Fantasy",
    director: "Tom Shadyac",
    writer:
      "Steve Koren (story), Mark O'Keefe (story), Steve Koren (screenplay), Mark O'Keefe (screenplay), Steve Oedekerk (screenplay)",
    actors: "Jim Carrey, Morgan Freeman, Jennifer Aniston, Philip Baker Hall",
    plot: "A guy who complains about God too often is given almighty powers to teach him how difficult it is to run the world.",
    language: "English, Spanish",
    country: "USA",
    awards: "7 wins & 9 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNzMyZDhiZDUtYWUyMi00ZDQxLWE4NDQtMWFlMjI1YjVjMjZiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "6.8/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "48%",
      },
      {
        source: "Metacritic",
        value: "46/100",
      },
    ],
    metascore: "46",
    imdbRating: "6.8",
    imdbVotes: "372,120",
    imdbID: "tt0315327",
    type: "movie",
    DVD: "01 Dec 2015",
    boxOffice: "$242,829,261",
    production: "Spyglass Entertainment",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 2,
    title: "Bad Boys for Life",
    year: "2020",
    rated: "R",
    released: "17 Jan 2020",
    runtime: "124 min",
    genre: "Action, Comedy, Crime, Thriller",
    director: "Adil El Arbi, Bilall Fallah",
    writer:
      "Peter Craig (story by), Joe Carnahan (story by), Chris Bremner (screenplay by), Peter Craig (screenplay by), Joe Carnahan (screenplay by), George Gallo (based on characters created by)",
    actors: "Will Smith, Martin Lawrence, Vanessa Hudgens, Alexander Ludwig",
    plot: "Miami detectives Mike Lowrey and Marcus Burnett must face off against a mother-and-son pair of drug lords who wreak vengeful havoc on their city.",
    language: "English, Spanish",
    country: "USA, Mexico",
    awards: "2 wins & 12 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMWU0MGYwZWQtMzcwYS00NWVhLTlkZTAtYWVjOTYwZTBhZTBiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "6.6/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "77%",
      },
      {
        source: "Metacritic",
        value: "59/100",
      },
    ],
    metascore: "59",
    imdbRating: "6.6",
    imdbVotes: "131,495",
    imdbID: "tt1502397",
    type: "movie",
    DVD: "31 Mar 2020",
    boxOffice: "$206,305,244",
    production: "2.0 Entertainment, Jerry Bruckheimer Films, Columbia Pictures",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 2,
    title: "Sausage Party",
    year: "2016",
    rated: "R",
    released: "12 Aug 2016",
    runtime: "89 min",
    genre: "Animation, Adventure, Comedy, Fantasy",
    director: "Greg Tiernan, Conrad Vernon",
    writer:
      "Kyle Hunter (screenplay by), Ariel Shaffir (screenplay by), Seth Rogen (screenplay by), Evan Goldberg (screenplay by), Seth Rogen (story by), Evan Goldberg (story by), Jonah Hill (story by)",
    actors: "Alistair Abell, Iris Apatow, Sugar Lyn Beard, Michael Cera",
    plot: "A sausage strives to discover the truth about his existence.",
    language: "English",
    country: "USA, Canada",
    awards: "1 win & 24 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjkxOTk1MzY4MF5BMl5BanBnXkFtZTgwODQzOTU5ODE@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "6.1/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "82%",
      },
      {
        source: "Metacritic",
        value: "66/100",
      },
    ],
    metascore: "66",
    imdbRating: "6.1",
    imdbVotes: "176,325",
    imdbID: "tt1700841",
    type: "movie",
    DVD: "04 Nov 2016",
    boxOffice: "$97,685,686",
    production: "Sony Music, Point Grey, Annapurna Pictures, Columbia Pictures",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 2,
    title: "A Dog's Purpose",
    year: "2017",
    rated: "PG",
    released: "27 Jan 2017",
    runtime: "100 min",
    genre: "Adventure, Comedy, Drama, Family, Fantasy",
    director: "Lasse Hallström",
    writer:
      "W. Bruce Cameron (screenplay by), Cathryn Michon (screenplay by), Audrey Wells (screenplay by), Maya Forbes (screenplay by), Wallace Wolodarsky (screenplay), W. Bruce Cameron (based on the novel by)",
    actors: "Josh Gad, Dennis Quaid, Peggy Lipton, Bryce Gheisar",
    plot: "A dog looks to discover his purpose in life over the course of several lifetimes and owners.",
    language: "English",
    country: "USA, India",
    awards: "3 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDQ4NjkxNzgzN15BMl5BanBnXkFtZTgwMjAzODQ4OTE@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "7.2/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "35%",
      },
      {
        source: "Metacritic",
        value: "43/100",
      },
    ],
    metascore: "43",
    imdbRating: "7.2",
    imdbVotes: "65,912",
    imdbID: "tt1753383",
    type: "movie",
    DVD: "18 Apr 2017",
    boxOffice: "$64,508,620",
    production:
      "Reliance Entertainment, Universal Pictures, Walden Media, Pariah",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 3,
    title: "Apollo 11",
    year: "2019",
    rated: "G",
    released: "01 Mar 2019",
    runtime: "93 min",
    genre: "Documentary, History",
    director: "Todd Douglas Miller",
    writer: "N/A",
    actors: "Neil Armstrong, Michael Collins, Buzz Aldrin, Deke Slayton",
    plot: "A look at the Apollo 11 mission to land on the moon led by commander Neil Armstrong and pilots Buzz Aldrin and Michael Collins.",
    language: "English",
    country: "USA",
    awards: "Won 3 Primetime Emmys. Another 52 wins & 42 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTYyMzEzNjI4M15BMl5BanBnXkFtZTgwODgxOTgyNzM@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "8.2/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "99%",
      },
      {
        source: "Metacritic",
        value: "88/100",
      },
    ],
    metascore: "88",
    imdbRating: "8.2",
    imdbVotes: "22,107",
    imdbID: "tt8760684",
    type: "movie",
    DVD: "14 May 2019",
    boxOffice: "$9,039,891",
    production: "CNN Films, Statement Pictures",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 3,
    title: "Kiss the Ground",
    year: "2020",
    rated: "N/A",
    released: "01 Apr 2020",
    runtime: "84 min",
    genre: "Documentary",
    director: "Joshua Tickell, Rebecca Harrell Tickell",
    writer: "Johnny O'Hara, Joshua Tickell, Rebecca Harrell Tickell",
    actors: "Woody Harrelson, Ray Archuleta, John Wick, Kristin Ohlson",
    plot: 'A revolutionary group of activists, scientists, farmers, and politicians band together in a global movement of "Regenerative Agriculture" that could balance our climate, replenish our vast water supplies, and feed the world',
    language: "English",
    country: "USA",
    awards: "4 wins & 4 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNmJkOWRhZWUtZmNlZC00NWYwLThiMmEtZjZkMTI4N2Y1NDMxXkEyXkFqcGdeQXVyMTE5NTc0NzY@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "8.3/10",
      },
    ],
    metascore: "N/A",
    imdbRating: "8.3",
    imdbVotes: "4,733",
    imdbID: "tt8618654",
    type: "movie",
    DVD: "N/A",
    boxOffice: "N/A",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 3,
    title: "The Game Changers",
    year: "2018",
    rated: "N/A",
    released: "16 Sep 2019",
    runtime: "86 min",
    genre: "Documentary",
    director: "Louie Psihoyos",
    writer: "Shannon Kornelsen (Co-w), Mark Monroe, Joseph Pace",
    actors:
      "James Wilks, Arnold Schwarzenegger, Patrik Baboumian, Dotsie Bausch",
    plot: "A UFC fighter's world is turned upside down when he discovers an elite group of world-renowned athletes and scientists who prove that everything he had been taught about protein was a lie.",
    language: "English",
    country: "USA",
    awards: "1 nomination.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMzg4ZjMzOWEtZjBhZi00MzgxLWEzNmItYjVlYjY0MGQ5ZmM5XkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "7.9/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "70%",
      },
    ],
    metascore: "N/A",
    imdbRating: "7.9",
    imdbVotes: "16,197",
    imdbID: "tt7455754",
    type: "movie",
    DVD: "01 Oct 2019",
    boxOffice: "$739,711",
    production:
      "Diamond Docs, ReFuel Productions, Oceanic Preservation Society",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 3,
    title: "American Factory",
    year: "2019",
    rated: "TV-14",
    released: "21 Aug 2019",
    runtime: "110 min",
    genre: "Documentary",
    director: "Steven Bognar, Julia Reichert",
    writer: "N/A",
    actors: "Junming 'Jimmy' Wang, Robert Allen, Sherrod Brown, Dave Burrows",
    plot: "In post-industrial Ohio, a Chinese billionaire opens a factory in an abandoned General Motors plant, hiring two thousand Americans. Early days of hope and optimism give way to setbacks as high-tech China clashes with working-class America.",
    language: "English, Mandarin",
    country: "USA",
    awards: "Won 1 Oscar. Another 18 wins & 48 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNWFkMDY1MjItZmNkOS00MDg2LWFlMjMtZWU3YmM0MmY3MWM3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "7.4/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "96%",
      },
      {
        source: "Metacritic",
        value: "86/100",
      },
    ],
    metascore: "86",
    imdbRating: "7.4",
    imdbVotes: "17,956",
    imdbID: "tt9351980",
    type: "movie",
    DVD: "21 Aug 2019",
    boxOffice: "N/A",
    production: "Participant Media",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 4,
    title: "The Blue Lagoon",
    year: "1980",
    rated: "R",
    released: "02 Jul 1980",
    runtime: "104 min",
    genre: "Adventure, Drama, Romance",
    director: "Randal Kleiser",
    writer:
      "Henry De Vere Stacpoole (based on the novel by), Douglas Day Stewart (screenplay by)",
    actors: "Brooke Shields, Christopher Atkins, Leo McKern, William Daniels",
    plot: "In the Victorian period, two children are shipwrecked on a tropical island in the South Pacific. With no adults to guide them, the two make a simple life together, unaware that sexual maturity will eventually intervene.",
    language: "English",
    country: "USA",
    awards: "Nominated for 1 Oscar. Another 4 wins & 7 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOWU2ZDIxY2UtNzM5NS00MWUwLTkxN2QtMmI3NDZkNTA2OTYxXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "10/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "8%",
      },
      {
        source: "Metacritic",
        value: "31/100",
      },
    ],
    metascore: "31",
    imdbRating: "5.8",
    imdbVotes: "63,278",
    imdbID: "tt0080453",
    type: "movie",
    DVD: "16 Apr 2012",
    boxOffice: "$58,853,106",
    production: "Columbia Pictures",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 4,
    title: "Gone Girl",
    year: "2014",
    rated: "R",
    released: "03 Oct 2014",
    runtime: "149 min",
    genre: "Drama, Mystery, Thriller",
    director: "David Fincher",
    writer: "Gillian Flynn (screenplay), Gillian Flynn (novel)",
    actors: "Ben Affleck, Rosamund Pike, Neil Patrick Harris, Tyler Perry",
    plot: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    language: "English",
    country: "USA",
    awards: "Nominated for 1 Oscar. Another 64 wins & 186 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "8.1/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "87%",
      },
      {
        source: "Metacritic",
        value: "79/100",
      },
    ],
    metascore: "79",
    imdbRating: "8.1",
    imdbVotes: "863,582",
    imdbID: "tt2267998",
    type: "movie",
    DVD: "01 Jun 2016",
    boxOffice: "$167,767,189",
    production: "TSG Entertainment",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 4,
    title: "The Revenant",
    year: "2015",
    rated: "R",
    released: "08 Jan 2016",
    runtime: "156 min",
    genre: "Action, Adventure, Drama, History, Western",
    director: "Alejandro G. Iñárritu",
    writer:
      "Mark L. Smith (screenplay), Alejandro G. Iñárritu (screenplay), Michael Punke (based in part on the novel by)",
    actors: "Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson, Will Poulter",
    plot: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
    language: "English, Pawnee, French",
    country: "USA, Hong Kong, Taiwan",
    awards: "Won 3 Oscars. Another 87 wins & 187 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMDE5OWMzM2QtOTU2ZS00NzAyLWI2MDEtOTRlYjIxZGM0OWRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "8.0/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "78%",
      },
      {
        source: "Metacritic",
        value: "76/100",
      },
    ],
    metascore: "76",
    imdbRating: "8.0",
    imdbVotes: "709,377",
    imdbID: "tt1663202",
    type: "movie",
    DVD: "22 Mar 2016",
    boxOffice: "$183,637,894",
    production: "Appian Way, New Regency Pictures, M Prods, Anonymous Content",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 4,
    title: "After",
    year: "2019",
    rated: "PG-13",
    released: "12 Apr 2019",
    runtime: "105 min",
    genre: "Drama, Romance",
    director: "Jenny Gage",
    writer:
      "Susan McMartin (screenplay by), Tamara Chestna (screenplay by), Jenny Gage (screenplay by), Tom Betterton (screenplay by), Anna Todd (based on the novel by)",
    actors:
      "Josephine Langford, Hero Fiennes Tiffin, Khadijha Red Thunder, Dylan Arnold",
    plot: "A young woman falls for a guy with a dark secret and the two embark on a rocky relationship. Based on the novel by Anna Todd.",
    language: "English",
    country: "USA",
    awards: "4 wins.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOGUwMjk3YzktNDI0Yy00MzFiLWFjNmEtYTA2ODVjMzNhODhjXkEyXkFqcGdeQXVyOTQ1MDI4MzY@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "5.3/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "18%",
      },
      {
        source: "Metacritic",
        value: "30/100",
      },
    ],
    metascore: "30",
    imdbRating: "5.3",
    imdbVotes: "38,125",
    imdbID: "tt4126476",
    type: "movie",
    DVD: "25 Jun 2019",
    boxOffice: "$12,138,565",
    production:
      "Wattpad, Offspring Entertainment, Diamond Film Productions, Voltage Pictures",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 5,
    title: "Mary",
    year: "2019",
    rated: "R",
    released: "11 Oct 2019",
    runtime: "84 min",
    genre: "Horror, Mystery",
    director: "Michael Goi",
    writer: "Anthony Jaswinski",
    actors: "Gary Oldman, Emily Mortimer, Manuel Garcia-Rulfo, Stefanie Scott",
    plot: "A family looking to start a charter-boat business buys a ship that holds terrifying secrets once out on isolated waters.",
    language: "English",
    country: "USA, Canada",
    awards: "1 nomination.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNzk1MGYyYmQtZjA3NC00ZWZiLTg1NWMtMjEwNTVlODM5OWVkXkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "4.4/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "4%",
      },
      {
        source: "Metacritic",
        value: "31/100",
      },
    ],
    metascore: "31",
    imdbRating: "4.4",
    imdbVotes: "3,094",
    imdbID: "tt5834854",
    type: "movie",
    DVD: "11 Oct 2019",
    boxOffice: "N/A",
    production: "Tucker Tooley Entertainment",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 5,
    title: "The Grudge",
    year: "2004",
    rated: "PG-13",
    released: "22 Oct 2004",
    runtime: "91 min",
    genre: "Horror, Mystery, Thriller",
    director: "Takashi Shimizu",
    writer:
      'Stephen Susco (screenplay), Takashi Shimizu (film "Ju-On: The Grudge")',
    actors: "Sarah Michelle Gellar, Jason Behr, William Mapother, Clea DuVall",
    plot: "An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse, one that locks a person in a powerful rage before claiming their life and spreading to another victim.",
    language: "English, Japanese",
    country: "USA, Japan",
    awards: "2 wins & 10 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjIxODg1Nzc3NF5BMl5BanBnXkFtZTcwMjM0MjEzMw@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "5.9/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "40%",
      },
      {
        source: "Metacritic",
        value: "49/100",
      },
    ],
    metascore: "49",
    imdbRating: "5.9",
    imdbVotes: "138,933",
    imdbID: "tt0391198",
    type: "movie",
    DVD: "18 Jun 2013",
    boxOffice: "$110,359,362",
    production: "Senator International, Ghost House Pictures",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 5,
    title: "Gretel & Hansel",
    year: "2020",
    rated: "PG-13",
    released: "31 Jan 2020",
    runtime: "87 min",
    genre: "Fantasy, Horror, Mystery, Thriller",
    director: "Oz Perkins",
    writer: "Rob Hayes",
    actors: "Sophia Lillis, Samuel Leakey, Alice Krige, Jessica De Gouw",
    plot: "A long time ago in a distant fairy tale countryside, a young girl leads her little brother into a dark wood in desperate search of food and work, only to stumble upon a nexus of terrifying evil.",
    language: "English",
    country: "USA, Canada, Ireland, South Africa",
    awards: "1 win & 11 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOTIyYWJjZDctODY4OC00NWExLWE2NTktZmY0MWY2YWZjMWIxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "5.4/10",
      },
      {
        source: "Metacritic",
        value: "64/100",
      },
    ],
    metascore: "64",
    imdbRating: "5.4",
    imdbVotes: "24,098",
    imdbID: "tt9086228",
    type: "movie",
    DVD: "N/A",
    boxOffice: "$15,347,654",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 5,
    title: "The Nun",
    year: "2018",
    rated: "R",
    released: "07 Sep 2018",
    runtime: "96 min",
    genre: "Horror, Mystery, Thriller",
    director: "Corin Hardy",
    writer:
      "Gary Dauberman (screenplay by), James Wan (story by), Gary Dauberman (story by)",
    actors: "Demián Bichir, Taissa Farmiga, Jonas Bloquet, Bonnie Aarons",
    plot: "A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania and confront a malevolent force in the form of a demonic nun.",
    language: "English, French, Romanian, Latin",
    country: "USA",
    awards: "2 wins & 1 nomination.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "5.3/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "25%",
      },
      {
        source: "Metacritic",
        value: "46/100",
      },
    ],
    metascore: "46",
    imdbRating: "5.3",
    imdbVotes: "119,020",
    imdbID: "tt5814060",
    type: "movie",
    DVD: "20 Nov 2018",
    boxOffice: "$117,450,119",
    production: "Atomic Monster, Safran Company",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 6,
    title: "100% Wolf",
    year: "2020",
    rated: "PG",
    released: "01 Dec 2020",
    runtime: "96 min",
    genre: "Animation, Adventure, Comedy, Family, Fantasy",
    director: "Alexs Stadermann",
    writer:
      "Ranald Allan (story contribution), David Breen (story contribution), Fin Edquist (screenplay by), Alexs Stadermann (head of story), Stephanie Zehnal (story contribution)",
    actors: "Loren Gray, Adriane Daff, Jane Lynch, Jai Courtney",
    plot: '100% Wolf centers on Freddy Lupin, heir to a proud family line of werewolves. Positive he\'ll become the most fearsome werewolf ever, Freddy is in for a shock when his first "warfing" goes awry, turning him into a ferocious - poodle.',
    language: "English",
    country: "Australia, Belgium",
    awards: "N/A",
    poster:
      "https://m.media-amazon.com/images/M/MV5BYmRiYTM3ZGMtNzA1Yy00OWQ1LWE2ZGEtZTRiYzYyZDZjYWYwXkEyXkFqcGdeQXVyMjMwODE4ODI@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "5.7/10",
      },
    ],
    metascore: "N/A",
    imdbRating: "5.7",
    imdbVotes: "782",
    imdbID: "tt8774798",
    type: "movie",
    DVD: "N/A",
    boxOffice: "$512,805",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 6,
    title: "Woody Woodpecker",
    year: "2017",
    rated: "PG",
    released: "22 Nov 2019",
    runtime: "91 min",
    genre: "Comedy, Family",
    director: "Alex Zamm",
    writer:
      "Alex Zamm, William Robertson, Walter Lantz (based on the character created by), Ben Hardaway (based on the character created by), Alex Zamm (story), William Robertson (story), Daniel Altiere (story), Steven Altiere (story)",
    actors: "Eric Bauza, Timothy Omundson, Graham Verchere, Jordana Largy",
    plot: "The hyperactive red-headed bird enters a turf war with a big city lawyer wanting to tear down his home in an effort to build a house to flip.",
    language: "English",
    country: "USA",
    awards: "N/A",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNjJjMmRkNjYtNmJhNi00ZDM1LWEzMjMtOWZjNjgxODc1YmFlXkEyXkFqcGdeQXVyOTQyNTIzNjM@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "4.1/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "13%",
      },
    ],
    metascore: "N/A",
    imdbRating: "4.1",
    imdbVotes: "3,543",
    imdbID: "tt2114504",
    type: "movie",
    DVD: "06 Feb 2018",
    boxOffice: "N/A",
    production:
      "Universal Studios Inc., Universal Pictures, Universal Studios Home Entertainment, Universal Studios Family Produ",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 6,
    title: "Ferdinand",
    year: "2017",
    rated: "PG",
    released: "15 Dec 2017",
    runtime: "108 min",
    genre: "Animation, Adventure, Comedy, Family, Fantasy",
    director: "Carlos Saldanha",
    writer:
      'Robert L. Baird (screenplay by), Tim Federle (screenplay by), Brad Copeland (screenplay by), Ron Burch (screen story by), David Kidd (screen story by), Don Rhymer (screen story by), Munro Leaf (based upon the book "The Story of Ferdinand" by), Robert Lawson (based upon the book "The Story of Ferdinand" by: illustrations)',
    actors: "Jack Gore, Jet Jurgensmeyer, Nile Diaz, Colin H. Murphy",
    plot: "After Ferdinand, a bull with a big heart, is mistaken for a dangerous beast, he is captured and torn from his home. Determined to return to his family, he rallies a misfit team on the ultimate adventure.",
    language: "English, Spanish, German",
    country: "USA, Spain",
    awards: "Nominated for 1 Oscar. Another 2 wins & 19 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOTIwMDI0NjQ4OF5BMl5BanBnXkFtZTgwNjU0MzAyNDM@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "6.7/10",
      },
      {
        source: "Rotten Tomatoes",
        value: "72%",
      },
      {
        source: "Metacritic",
        value: "58/100",
      },
    ],
    metascore: "58",
    imdbRating: "6.7",
    imdbVotes: "48,883",
    imdbID: "tt3411444",
    type: "movie",
    DVD: "23 Feb 2018",
    boxOffice: "$84,410,380",
    production: "Blue Sky Studios",
    website: "N/A",
    response: "True",
  },
  {
    genre_id: 6,
    title: "Pets United",
    year: "2019",
    rated: "TV-Y7",
    released: "11 Sep 2020",
    runtime: "89 min",
    genre: "Animation, Adventure, Comedy",
    director: "Reinhard Klooss",
    writer:
      "Reinhard Klooss, Reinhard Klooss (based on the story by), Oliver Huzly (based on the story by)",
    actors: "Patrick Roche, Natalie Dormer, Felix Auer, Jeff Burrell",
    plot: "A group of spoilt, selfish pets led by glamour cat Belle are stranded in their luxury hangout 'Pampered Pets,' when the machines that run Robo City, the hypermodern metropolis that they live in, go wild and take over.",
    language: "English",
    country: "Germany, China, UK",
    awards: "N/A",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNmU2YTEwODktZDFlNC00YWJmLTk0NjEtMzZjMjM4Y2E3NjdiXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
    ratings: [
      {
        source: "Internet Movie Database",
        value: "3.8/10",
      },
    ],
    metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "1,858",
    imdbID: "tt11276598",
    type: "movie",
    DVD: "N/A",
    boxOffice: "N/A",
    production: "N/A",
    website: "N/A",
    response: "True",
  },
];

export const genres = ["action", "comedy", "adventure", "horror"];
